# Generated by Django 2.2.3 on 2022-04-08 07:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220408_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 7, 44, 44, 507488, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
